### PR TITLE
small fix to work with relay environment

### PR DESCRIPTION
**Pull request by sibelius**
[DO NOT MERGE]

we need to figure it way the best way to handle queries parameters

### CODE REVIEW

**Comment by proProbe** [comment]
+1

**Comment by Naoto-Ida** [comment]
Is this referring to an issue like this:

``` js
<Scene
  key="foo"
  queries={{viewer: () => Relay.QL`query { viewer(language: en) }`}}
/>
```

Where I can't give an initial value for `language` other than hardcoding it right now?

**Comment by sibelius** [comment]
@Naoto-Ida you should pass $language as a Scene parameter

for instance:

``` js
<Scene
  key="foo"
  queries={{viewer: () => Relay.QL`query { viewer(language: $language) }`}}
/>

Actions.foo({language: 'en'})
```

I think language should be an user preference, instead of being passed as a parameter in all queries

**Comment by sibelius** [comment]
this PR only fixes the case when u try to use a custom RelayEnvironment

**Comment by r0b1n** [comment]
@sibelius is it safe to merge this PR?

**Comment by sibelius** [comment]
it is safe, I'm using on production and works well with a custom Relay Environment

**Comment by r0b1n** [comment]
@sibelius thanks, merged! Will test it at weekend and publish new `npm` version from the master.

**Comment by Naoto-Ida** [comment]
@sibelius Thanks. But how would I pass variables to the initial Component? Do I intentionally need to make an empty container set to `initial` that calls `Actions.foo({language: 'en'})` then transition into the actual initial container? Your new PR allows us to plug in variables right?

**Comment by sibelius** [comment]
@Naoto-Ida my PR addresses the use of a custom Relay.Environment with rnrf-relay-renderer

all variables that u pass using `Actions.foo({language: 'en'})` will be available to ur Relay.createContainer, but u should set this variable as null,

for instance

``` js
export default Relay.createContainer(Post, {
  initialVariables: {
    id: null,
  },
  fragments: {
    viewer: () => Relay.QL`
      fragment on Viewer {
        post(id: $id){
          id,
          body
      }
    }
    `,
  },
});
```

u can call `Actions.post({id: 'post_id'})`

**Pull request merged**
